s-panferov/valico

Cargo.toml, build.rs, src/common/error.rs, src/json_dsl/builder.rs, src/json_dsl/coercers.rs, src/json_dsl/mod.rs, src/json_dsl/param.rs, src/json_schema/keywords/format.rs, src/json_schema/keywords/mod.rs, src/json_schema/schema.rs, src/json_schema/validators/dependencies.rs, src/json_schema/validators/items.rs, src/json_schema/validators/mod.rs, src/json_schema/validators/of.rs, src/json_schema/validators/properties.rs, src/lib.rs, tests/dsl/helpers.rs, tests/dsl/mod.rs, tests/schema/mod.rs, tests/tests.rs
Fix for #9 
Summary:
* Replace `phf_macros` with `phf_codegen`
* Replace `regex_macros` with `lazy_static`
* Replace `mopy` with `typeable` and `traitobject`
* Replace `Vec::append` with `Extend::extend`
* Replace `path::is_file` with `File::metadata().is_file()`
All unit tests appear to be passing.
=> refactor(*): rustc 1.0.0-beta.4

src/json_schema/keywords/format.rs
The current regex does not allow for a colon in the time offset part of the regex. ISO 8601 permits this colon, whereas RFC 3339, which is a subset of said ISO spec, **requires** it to be there. This change makes it stay 8601 conformant while also making it accept RFC 3339 formatted dates.
=> RFC 3339 conformity in the date parsing regex

build.rs
Read OUT_DIR at runtime allows to fix cross compilation issue
=> fix(build): read OUT_DIR at runtime instead of compile time

Cargo.toml, src/common/error.rs, src/json_dsl/builder.rs, src/json_dsl/coercers.rs, src/json_dsl/errors.rs, src/json_dsl/param.rs, src/json_schema/builder.rs, src/json_schema/errors.rs, src/json_schema/helpers.rs, src/json_schema/keywords/enum_.rs, src/json_schema/keywords/format.rs, src/json_schema/keywords/items.rs, src/json_schema/keywords/maxmin.rs, src/json_schema/keywords/maxmin_items.rs, src/json_schema/keywords/maxmin_length.rs, src/json_schema/keywords/maxmin_properties.rs, src/json_schema/keywords/mod.rs, src/json_schema/keywords/multiple_of.rs, src/json_schema/keywords/of.rs, src/json_schema/keywords/pattern.rs, src/json_schema/keywords/properties.rs, src/json_schema/keywords/ref_.rs, src/json_schema/keywords/type_.rs, src/json_schema/keywords/unique_items.rs, src/json_schema/validators/dependencies.rs, src/json_schema/validators/mod.rs, tests/dsl/mod.rs, tests/schema/mod.rs
* BREAKING CHANGE: Force the current doc examples to `unwrap` their code, since now
`serde_json::to_value` returns a `Result`.
* BREAKING CHANGE: Make downstream update any custom serializers they may have used to conform to the new `serde` API. This is expected, and not too big of a deal for people who want to upgrade to the new versions of `serde`. Basically, one only needs to change the `&mut S` argument to `S`, and use `S::Ok` instead of `()` for the `Result`.
* BREAKING CHANGE: Rename `find` usages in the docs to its isomorphic successor API `get`.
* BREAKING CHANGE: Replace `find_path` usages in the docs with usages of the new `pointer` API.
Closes issue #26.
---
NOTE that this PR is distinct from https://github.com/rustless/valico/pull/27, which has a few broken tests. This PR has …
=> Update to `serde` 1.0 with tests still passing

Cargo.toml
Hey
Updating this crate to 0.6 since the new release is out. There are no further changes required.
=> chore(*): update uuid to 0.6

CONTRIBUTING.md
It's not immediately obvious that one must get the submodules in order to run tests!
Another way to fix this would be to make the test check to see if the directory exists instead of simply panicking.
Fixes #33
=> Notes need to clone with submodules in CONTRIBUTING

src/json_schema/builder.rs
I'm having trouble tracking down where this is in the spec, but virtually every example linked from http://json-schema.org/examples.html contains descriptions within the top-level and property definitions.
This meets my needs for a more self-documenting schema.
If it's desirable, I'd like to do the same for the "title" property, although it only makes sense at the top level and I'm not sure how to limit it to that scope.
=> feat(json_schema): Adds a schema builder function for the description property

src/json_schema/builder.rs
Title is only valid at the top level, but there is not currently a way
to limit that at compile time.
=> feat(json_schema): Adds title convenience method

Cargo.toml
Updates uuid to 0.7. Have gone through the usages of uuid in the codebase and no other change is needed.
=> chore(*): update uuid to 0.7

Cargo.toml
I want to use valico in a tool I'm writing, but I had to get the `regex-syntax` crate to [update their licenses](https://github.com/rust-lang/regex/issues/530) to be able to use it in my org. The `valico` crate won't pull in these changes unless it uses the new version of the `regex` crate.
Bumping the version to `1.0` in the `Cargo.toml` still allows valico to build, so I'm hoping this change is pretty harmless.
=> chore(Cargo.toml): bump version of regex

README.md
I don't have time to update the rest of the examples, but hopefully this will at least save users some time by showing how things are done in the modern API.
=> docs(json_schema): update suggested version and first example

Cargo.toml, src/common/error.rs, src/lib.rs
Removes dependencies on the traitobject and typeable crates, as neither
crate includes a proper LICENSE file in the repo.
The author of both traitobject and typeable didn't include a LICENSE file in either repository, and [isn't responsive](https://github.com/reem/rust-traitobject/issues/4) to [github issues](https://github.com/reem/rust-typeable/issues/10) asking for this to be addressed. This is preventing me from using valico. Luckily, the changes necessary to remove these dependencies are fairly straightforward.
My apologies for not including this with my last PR.
=> refactor(lib, common): remove traitobject, typeable

Cargo.toml, src/json_schema/keywords/format.rs, src/json_schema/keywords/mod.rs, src/json_schema/keywords/ref_.rs, src/json_schema/schema.rs, src/json_schema/validators/formats.rs, src/lib.rs, tests/schema/mod.rs
I updated the dependency of JSON-Schema-Test-Suite to tag 2.0.0 (still on draft4, just updated tests).
In doing so I also noticed that:
- several formats are not implemented according to spec and reimplemented them (date-time, email, hostname).
- `$ref` behavior isn't identical to the spec (if there are other properties on the same level, they compose with the properties that the `$ref` is pointing to).
=> Refresh tests dependency and formats

README.md, src/json_schema/helpers.rs, src/json_schema/validators/const_.rs, src/json_schema/validators/enum_.rs, tests/schema/mod.rs
New tests were added for the draft6. Notably the matching between booleans and numbers. But also some JS ECMA regex rules which the `regex` crate doesn't support - I skipped these tests but I don't know if `valico` should try hard to be compliant on these "optional" rules?
=> fix(json_schema): Handle new draft6 tests

src/json_schema/validators/properties.rs
Include the name of the unallowed property name in the errors::Properties details, enabling users to more precisely pin-point the issue in the JSON document.
The previous error required users to go back to the schema to know how to fix their JSON documents. Alternatively, the error's `path` could be changed to include the `key`, but that would potentially break backwards compatibility.
=> feat(json_schema): include unallowed additional property name in error detail

Cargo.toml, README.md, src/common/error.rs, src/json_dsl/errors.rs, src/json_schema/builder.rs, src/json_schema/errors.rs, src/json_schema/helpers.rs, src/json_schema/keywords/conditional.rs, src/json_schema/keywords/content_media.rs, src/json_schema/keywords/format.rs, src/json_schema/keywords/maxmin_items.rs, src/json_schema/keywords/maxmin_length.rs, src/json_schema/keywords/maxmin_properties.rs, src/json_schema/keywords/mod.rs, src/json_schema/keywords/type_.rs, src/json_schema/keywords/unique_items.rs, src/json_schema/validators/conditional.rs, src/json_schema/validators/content_media.rs, src/json_schema/validators/formats.rs, src/json_schema/validators/mod.rs, tests/schema/mod.rs
Closes #32.
Here's my attempt to support draft 7. It has limitations, most notably:
- `contentMediaType` and `contentEncoding` only support `application/json` and `base64` but I wanted to get some feedback on my implementation -- maybe that can be addressed in the future;
- the lack of support for remote refs/schemas, but this is already a current gap in Valico, and I propose to address it separately;
- the `time` format doesn't really conform to the standard because of https://github.com/chronotope/chrono/issues/288;
- https://github.com/remexre/json-pointer doesn't support relative pointers... yet;
- https://github.com/chowdhurya/rust-uritemplate needs better error handling; and
- the are keywords listed on https://json-schema.org/draft-07/json-schema-release-notes.html that don't seem …
=> feat(json_schema): Draft 7

src/json_schema/helpers.rs, src/json_schema/schema.rs
This fixes two compilation warnings due to using deprecated functions.
=> fix(json_schema): Replace deprecated function url::Url::into_string()

src/json_schema/validators/formats.rs
Forward slash (`/`) is prefixed with double backslash (`\\`)
in a JSON string. Although this is valid in JSON, this will fail
regex parsing in the rust `Regex` library, which will error when
parsing an escaped forward slash.
This string replacement ensures that escaped forward slashes do
not fail validation.
Fixes #73
=> Handle escaped forward slashes `\\/`

Cargo.toml, src/json_schema/validators/formats.rs
In https://github.com/chronotope/chrono/pull/473, chrono changed how %Z is handled, and was changed to simply skip over any non-whitespace characters in the timezone section, just like glibc's `strptime`.
I'm not sure if this is the right fix, but it gets the tests to pass.
=> Fix time tests

.github/workflows/ci.yml, src/common/error.rs
Fixes #88 
This PR ensures that `dyn ValicoError` is serialized the same as a concrete implementation of `ValicoError`. This allows `ValidationState` to be serialized correctly.
Please let me know if there's a better way to do this! :)
=> fix: Improve serialization of dyn ValicoError
